/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The backup key result, containing the backup blob.
 *
 */
class BackupKeyResult {
  /**
   * Create a BackupKeyResult.
   * @property {buffer} [value] The backup blob containing the backed up key.
   */
  constructor() {
  }

  /**
   * Defines the metadata of BackupKeyResult
   *
   * @returns {object} metadata of BackupKeyResult
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'BackupKeyResult',
      type: {
        name: 'Composite',
        className: 'BackupKeyResult',
        modelProperties: {
          value: {
            required: false,
            readOnly: true,
            serializedName: 'value',
            type: {
              name: 'Base64Url'
            }
          }
        }
      }
    };
  }
}

module.exports = BackupKeyResult;
