/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * A list of keys that have been deleted in this vault.
 */
class DeletedKeyListResult extends Array {
  /**
   * Create a DeletedKeyListResult.
   * @property {string} [nextLink] The URL to get the next set of deleted keys.
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of DeletedKeyListResult
   *
   * @returns {object} metadata of DeletedKeyListResult
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'DeletedKeyListResult',
      type: {
        name: 'Composite',
        className: 'DeletedKeyListResult',
        modelProperties: {
          value: {
            required: false,
            readOnly: true,
            serializedName: '',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'DeletedKeyItemElementType',
                  type: {
                    name: 'Composite',
                    className: 'DeletedKeyItem'
                  }
              }
            }
          },
          nextLink: {
            required: false,
            readOnly: true,
            serializedName: 'nextLink',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = DeletedKeyListResult;
