/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The deleted SAS definition list result
 */
class DeletedSasDefinitionListResult extends Array {
  /**
   * Create a DeletedSasDefinitionListResult.
   * @property {string} [nextLink] The URL to get the next set of deleted SAS
   * definitions.
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of DeletedSasDefinitionListResult
   *
   * @returns {object} metadata of DeletedSasDefinitionListResult
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'DeletedSasDefinitionListResult',
      type: {
        name: 'Composite',
        className: 'DeletedSasDefinitionListResult',
        modelProperties: {
          value: {
            required: false,
            readOnly: true,
            serializedName: '',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'DeletedSasDefinitionItemElementType',
                  type: {
                    name: 'Composite',
                    className: 'DeletedSasDefinitionItem'
                  }
              }
            }
          },
          nextLink: {
            required: false,
            readOnly: true,
            serializedName: 'nextLink',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = DeletedSasDefinitionListResult;
