/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The key list result.
 */
class KeyListResult extends Array {
  /**
   * Create a KeyListResult.
   * @property {string} [nextLink] The URL to get the next set of keys.
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of KeyListResult
   *
   * @returns {object} metadata of KeyListResult
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'KeyListResult',
      type: {
        name: 'Composite',
        className: 'KeyListResult',
        modelProperties: {
          value: {
            required: false,
            readOnly: true,
            serializedName: '',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'KeyItemElementType',
                  type: {
                    name: 'Composite',
                    className: 'KeyItem'
                  }
              }
            }
          },
          nextLink: {
            required: false,
            readOnly: true,
            serializedName: 'nextLink',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = KeyListResult;
