/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The key operation result.
 *
 */
class KeyOperationResult {
  /**
   * Create a KeyOperationResult.
   * @property {string} [kid] Key identifier
   * @property {buffer} [result]
   */
  constructor() {
  }

  /**
   * Defines the metadata of KeyOperationResult
   *
   * @returns {object} metadata of KeyOperationResult
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'KeyOperationResult',
      type: {
        name: 'Composite',
        className: 'KeyOperationResult',
        modelProperties: {
          kid: {
            required: false,
            readOnly: true,
            serializedName: 'kid',
            type: {
              name: 'String'
            }
          },
          result: {
            required: false,
            readOnly: true,
            serializedName: 'value',
            type: {
              name: 'Base64Url'
            }
          }
        }
      }
    };
  }
}

module.exports = KeyOperationResult;
