/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The key verify result.
 *
 */
class KeyVerifyResult {
  /**
   * Create a KeyVerifyResult.
   * @property {boolean} [value] True if the signature is verified, otherwise
   * false.
   */
  constructor() {
  }

  /**
   * Defines the metadata of KeyVerifyResult
   *
   * @returns {object} metadata of KeyVerifyResult
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'KeyVerifyResult',
      type: {
        name: 'Composite',
        className: 'KeyVerifyResult',
        modelProperties: {
          value: {
            required: false,
            readOnly: true,
            serializedName: 'value',
            type: {
              name: 'Boolean'
            }
          }
        }
      }
    };
  }
}

module.exports = KeyVerifyResult;
