/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The storage accounts list result.
 */
class StorageListResult extends Array {
  /**
   * Create a StorageListResult.
   * @property {string} [nextLink] The URL to get the next set of storage
   * accounts.
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of StorageListResult
   *
   * @returns {object} metadata of StorageListResult
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'StorageListResult',
      type: {
        name: 'Composite',
        className: 'StorageListResult',
        modelProperties: {
          value: {
            required: false,
            readOnly: true,
            serializedName: '',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'StorageAccountItemElementType',
                  type: {
                    name: 'Composite',
                    className: 'StorageAccountItem'
                  }
              }
            }
          },
          nextLink: {
            required: false,
            readOnly: true,
            serializedName: 'nextLink',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = StorageListResult;
