/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The secret restore parameters.
 *
 */
class StorageRestoreParameters {
  /**
   * Create a StorageRestoreParameters.
   * @property {buffer} storageBundleBackup The backup blob associated with a
   * storage account.
   */
  constructor() {
  }

  /**
   * Defines the metadata of StorageRestoreParameters
   *
   * @returns {object} metadata of StorageRestoreParameters
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'StorageRestoreParameters',
      type: {
        name: 'Composite',
        className: 'StorageRestoreParameters',
        modelProperties: {
          storageBundleBackup: {
            required: true,
            serializedName: 'value',
            type: {
              name: 'Base64Url'
            }
          }
        }
      }
    };
  }
}

module.exports = StorageRestoreParameters;
